### PR TITLE
Appreciate types

### PR DESCRIPTION
**Pull request by kungfooman**
TypeScript's autocompletion etc. is quite useful, but only when types are not ignored 😅 

I reversed the types from given example code in this repo and the engine itself + JSDoc

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
The `AnimComponent` API will be made public next week. I think we should revisit this PR then (and hopefully we won't need the additional `.d.ts` file).

**Comment by kungfooman** [comment]
This PR is depending on this PR now: https://github.com/playcanvas/engine/pull/2986

**Comment by willeastcott** [comment]
I definitely don't think we should be checking in an augmentation of the base engine TS definitions into this project. We should be addressing deficiencies in the TS defs upstream in the engine repo. As it happens, a lot of issues have already been addressed, with the AnimComponent and related classes now released into the public API. So I'd suggest closing this now, especially since #132 has gone even further to remove many `ts-ignore` directives.

**Comment by kungfooman** [comment]
I agree that PC types should be in the engine repo, therefore the code in your PR doesn't meet your own criterion:

```ts
const states : Array<{ name: string, speed?: number }> = [{ name: 'START' }];
```

While in my PR I link it to the actual/full type of allowed values, with the benefit of easy IntelliSense/auto-complete:

```ts
const states: pc.AnimStateGraphDataState[] = [{ name: 'START' }];
```

As soon as the engine breaks the API, the presence of "0 TS errors" may make you feel secure, but its an illusionary type safety.

Of course I also don't want the extra `playcanvas-augment.d.ts`, it was just the quickest way to sort out the required types by inferring it from the code until engine PR's were merged. Since the extra JSDoc comments swamp the file and you don't like that, I guess you want to settle with halfhearted aiding types like that.

**Comment by willeastcott** [comment]
Well, my PR is supposed to be an incremental improvement and does not set out to fix absolutely everything all at the same time. Like I say in that PR, it's also spawned a few engine repo issues that request fixes for a few TS definition problems.

I think I've mentioned previously that I still don't understand how typedefs can make it into the TS defs but not add phantom types or dead links to the API reference manual. Are these concerns justified or should I not worry about that?

**Comment by kungfooman** [comment]
> I think I've mentioned previously that I still don't understand how typedefs can make it into the TS defs but not add phantom types or dead links to the API reference manual. Are these concerns justified or should I not worry about that?

Dead links in the API reference manual are valid concerns, so I just took a look how typedef pages can be generated:

image

From:

```js
/**
 * @typedef {object} AnimStateGraph_DataFromObjectLayer
 * @property {string} name Name of this layer
 * @property {number[] | AnimStateGraph_DataState[]} states States of this layer
 * @property {number[] | AnimStateGraph_DataTransition} transitions Transitions of this layer
 */
```

It just needs a few lines in `jsdoc-template/publish.js` somewhere after `var classes =` to generate:

```js
        data({ kind: "typedef" }).each(function (doclet) {
            if (doclet.comment.includes('@typedef')) {
                classes.push(doclet);
            }
        });
```

It's not perfect, because it just reuses the `page.tmpl`, so it requires a few tweaks here and there.

Its a matter of priority, do people value the API reference manual over IntelliSense? I prefer IntelliSense, because it helps me in the place I am coding, so I would rather have a few broken links in the manual than lack of typing information in my projects I invest all my time into.

**Comment by willeastcott** [comment]
So I just had a meeting @ellthompson and he feels that it was probably a mistake to make the `AnimStateGraph` API public. So I suspect this will be made private in a forthcoming release. I've addressed the majority of the other `ts-ignore` issues already and I've logged engine issues about what's left. So I'm not sure if you think it's worth keeping this PR open?

**Comment by kungfooman** [comment]
Yea, it was probably a mistake, so this can be closed. 👍

**Pull request closed without merging**
