### PR TITLE
viewer is now on /model-viewer instead of /viewer

### PR DESCRIPTION
**Pull request by yak32**
Fixes #

support for internal changes on the backend - base path for the viewer is now /model-viewer instead of /viewer

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by yaustar** [comment]
Will /viewer still work? If not, have the Editor links been updated as well for 'Open in Viewer' context menu on GLB assets?

image

image

**Comment by mvaligursky** [comment]
does it mean this link will no longer work?
https://playcanvas.com/viewer

**Comment by yak32** [comment]
> does it mean this link will no longer work? https://playcanvas.com/viewer

we decided with Donovan to have redirection from viewer to model-viewer

**Comment by yak32** [comment]
> Will /viewer still work? If not, have the Editor links been updated as well for 'Open in Viewer' context menu on GLB assets? Or does this not matter?
> 
> image
> 
> image

links are updated, we also will have redirect from viewer to model-viewer

**Review by ellthompson — APPROVED** [review]

**Pull request merged**
